apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
  labels:
    app: currency-conversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - name: app
          image: currency-conversion:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: currency-config
            - secretRef:
                name: currency-secret
