"""create currency conversions table

Revision ID: 40ced1c2d0e0
Revises: 
Create Date: 2025-05-29 18:57:55.450748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ced1c2d0e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_conversions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('source_currency', sa.String(), nullable=True),
    sa.Column('source_amount', sa.Float(), nullable=True),
    sa.Column('target_currency', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_conversions_id'), 'currency_conversions', ['id'], unique=False)
    op.create_index(op.f('ix_currency_conversions_user_id'), 'currency_conversions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_conversions_user_id'), table_name='currency_conversions')
    op.drop_index(op.f('ix_currency_conversions_id'), table_name='currency_conversions')
    op.drop_table('currency_conversions')
    # ### end Alembic commands ###
