"""change id and user_id to UUID and implements Currency enum

Revision ID: 69fa7fccec6e
Revises: 40ced1c2d0e0
Create Date: 2025-05-29 19:10:08.977690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fa7fccec6e'
down_revision: Union[str, None] = '40ced1c2d0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
